spring:
  application:
    name: demo
  profiles:
    active: dev
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.web-allow-others: true
---
spring:
  config:
    activate:
      on-profile: dev
datasource:
  url: jdbc:h2:mem:demodb;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: password
  driverClassName: org.h2.Driver
  defaultSchema:
  maxPoolSize: 20
  hibernate:
    hbm2ddl.method: create-drop
    show_sql: true
    format_sql: true
    dialect: org.hibernate.dialect.H2Dialect
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true